export default function BattlecardPage() {
  return (
    <div className="p-6">
      <div className="max-w-4xl mx-auto">
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="bg-blue-800 text-white p-6">
            <div className="text-xs font-medium text-blue-200 uppercase tracking-wider">AI-Generated Negotiation Battlecard</div>
            <h2 className="mt-1 text-xl font-bold">Huggies — Nappies & Wipes</h2>
            <p className="mt-1 text-sm text-blue-200">Generated by Cortex AI | May 2026 | Confidential</p>
          </div>
          <div className="p-6 space-y-6">
            <div>
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wide mb-3">Sell-Through Position</h3>
              <div className="grid grid-cols-3 gap-4">
                <div className="p-3 bg-slate-50 rounded-lg"><div className="text-xs text-slate-500">Trend</div><div className="font-mono font-bold">Flat (0%)</div><div className="text-xs text-slate-500">vs +4% category</div></div>
                <div className="p-3 bg-slate-50 rounded-lg"><div className="text-xs text-slate-500">Market Share</div><div className="font-mono font-bold">42%</div><div className="text-xs text-red-500">-2pp vs LY</div></div>
                <div className="p-3 bg-slate-50 rounded-lg"><div className="text-xs text-slate-500">Rate of Sale</div><div className="font-mono font-bold">18.2/wk</div><div className="text-xs text-slate-500">Stable</div></div>
              </div>
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wide mb-3">Customer Value</h3>
              <ul className="space-y-1.5 text-sm text-slate-700">
                <li className="flex items-start gap-2"><span className="text-emerald-600">+</span><strong>Gateway brand:</strong> 70% of category customers enter via Huggies</li>
                <li className="flex items-start gap-2"><span className="text-emerald-600">+</span><strong>High CLV:</strong> 40% more lifetime spend than category average</li>
                <li className="flex items-start gap-2"><span className="text-emerald-600">+</span><strong>Retention:</strong> 72% still active at 12 months (vs 58% avg)</li>
              </ul>
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wide mb-3">Promo Effectiveness</h3>
              <ul className="space-y-1.5 text-sm text-slate-700">
                <li className="flex items-start gap-2"><span className="text-red-600">!</span>Deep discounts (30% off) are <strong>mostly pull-forward</strong> — only 40% incremental</li>
                <li className="flex items-start gap-2"><span className="text-red-600">!</span>Promo ROI: 0.8x (below break-even)</li>
                <li className="flex items-start gap-2"><span className="text-emerald-600">+</span>Bundles deliver 2.1x ROI — shift here</li>
              </ul>
            </div>
            <div className="border-t border-slate-200 pt-6">
              <h3 className="text-sm font-bold text-blue-800 uppercase tracking-wide mb-3">Recommended Negotiation Levers</h3>
              <div className="space-y-3">
                <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg text-sm text-blue-900"><strong>1.</strong> Shift promo investment from % off to bundles/GWP. Request co-op marketing for bundles.</div>
                <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg text-sm text-blue-900"><strong>2.</strong> Request exclusive pack sizes to neutralize direct price comparison with Coles.</div>
                <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg text-sm text-blue-900"><strong>3.</strong> Leverage gateway brand status — 70% new customers. Argue for better terms on acquisition value.</div>
                <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg text-sm text-amber-900"><strong>4.</strong> Flag eco-segment risk. Rascal + Friends growing. Ask for eco-range roadmap.</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
