import { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { ChevronRight, Loader2, Gift, AlertTriangle, Target } from "lucide-react";
import { brandData, categories } from "../data/brandConfig";

interface KeyArgument {
  name: string;
  description: string;
  data: string;
  argument: string;
  ask: string;
  impact: number;
}

interface BattlecardData {
  key_arguments: {
    profitability: KeyArgument[];
    growth: KeyArgument[];
    others: KeyArgument[];
  } | null;
  incentives: string[] | null;
  pressures: string[] | null;
  negotiation_approach: string | null;
  total_addressable: string | null;
  sellthrough: string;
  switching: string;
  summary: string;
}

function ImpactDots({ level }: { level: number }) {
  return (
    <div className="flex gap-0.5">
      {[1, 2, 3, 4, 5].map((i) => (
        <div
          key={i}
          className={`w-2.5 h-2.5 rounded-full ${i <= level ? "bg-blue-600" : "bg-slate-200"}`}
        />
      ))}
    </div>
  );
}

function ArgumentGroup({
  title,
  color,
  items,
}: {
  title: string;
  color: string;
  items: KeyArgument[];
}) {
  const borderColors: Record<string, string> = {
    red: "border-l-red-500",
    amber: "border-l-amber-500",
    slate: "border-l-slate-400",
  };

  return (
    <>
      <tr>
        <td
          colSpan={5}
          className={`bg-slate-50 px-4 py-2 font-bold text-xs uppercase tracking-wider text-slate-700 border-l-4 ${borderColors[color]}`}
        >
          {title}
        </td>
      </tr>
      {items.map((item, idx) => (
        <tr key={idx} className={`border-b border-slate-100 border-l-4 ${borderColors[color]}`}>
          <td className="px-4 py-3 align-top w-[18%]">
            <div className="font-semibold text-sm text-slate-900">{item.name}</div>
            <div className="text-xs text-slate-500 mt-0.5">{item.description}</div>
          </td>
          <td className="px-4 py-3 align-top text-xs text-slate-700 w-[22%]">{item.data}</td>
          <td className="px-4 py-3 align-top text-xs text-slate-700 w-[24%]">{item.argument}</td>
          <td className="px-4 py-3 align-top text-xs text-slate-700 w-[24%]">{item.ask}</td>
          <td className="px-4 py-3 align-top w-[12%]">
            <ImpactDots level={item.impact} />
          </td>
        </tr>
      ))}
    </>
  );
}

export default function BattlecardDetailPage() {
  const { brandName } = useParams();
  const brand = decodeURIComponent(brandName || "");
  const data = brandData[brand];
  const [battlecard, setBattlecard] = useState<BattlecardData | null>(null);
  const [loading, setLoading] = useState(true);

  const category = data
    ? categories.find((c) => c.name === data.category)
    : null;

  useEffect(() => {
    if (!data) return;
    const generate = async () => {
      setLoading(true);
      try {
        const res = await fetch("/api/battlecard/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ brand, category: data.category }),
        });
        const result = await res.json();
        setBattlecard(result);
      } catch {
        setBattlecard(null);
      } finally {
        setLoading(false);
      }
    };
    generate();
  }, [brand, data]);

  if (!data) {
    return (
      <div className="p-6">
        <Link to="/dashboard" className="text-blue-700 hover:underline text-sm">← Back to Dashboard</Link>
        <p className="mt-4 text-slate-500">Brand not found.</p>
      </div>
    );
  }

  return (
    <div className="p-6">
      <nav className="flex items-center gap-1.5 text-sm text-slate-500 mb-4">
        <Link to="/dashboard" className="hover:text-blue-700">Dashboard</Link>
        <ChevronRight className="w-3.5 h-3.5" />
        {category && (
          <>
            <Link to={`/category/${category.slug}`} className="hover:text-blue-700">{data.category}</Link>
            <ChevronRight className="w-3.5 h-3.5" />
          </>
        )}
        <Link to={`/brand/${encodeURIComponent(brand)}`} className="hover:text-blue-700">{brand}</Link>
        <ChevronRight className="w-3.5 h-3.5" />
        <span className="text-slate-900 font-medium">Battlecard</span>
      </nav>

      <div className="bg-blue-800 text-white px-6 py-4 rounded-t-xl">
        <div className="text-xs font-medium text-blue-200 uppercase tracking-wider">AI-Generated Negotiation Battlecard</div>
        <h1 className="text-lg font-bold mt-0.5">{data.category.toUpperCase()} — {brand}</h1>
        <p className="text-xs text-blue-200 mt-0.5">Generated by Cortex AI | May 2026 | Confidential</p>
      </div>

      {loading ? (
        <div className="bg-white border border-t-0 border-slate-200 rounded-b-xl p-12 flex flex-col items-center justify-center">
          <Loader2 className="w-8 h-8 animate-spin text-blue-500 mb-3" />
          <p className="text-sm text-slate-500">Cortex AI is generating your battlecard...</p>
        </div>
      ) : battlecard?.key_arguments ? (
        <div className="bg-white border border-t-0 border-slate-200 rounded-b-xl">
          <div className="grid grid-cols-[2fr_1fr] divide-x divide-slate-200">
            <div className="p-0">
              <table className="w-full text-left">
                <thead>
                  <tr className="border-b border-slate-200 bg-slate-50">
                    <th className="px-4 py-2 text-xs font-semibold text-slate-600 uppercase">Key Argument</th>
                    <th className="px-4 py-2 text-xs font-semibold text-slate-600 uppercase">Brand Data</th>
                    <th className="px-4 py-2 text-xs font-semibold text-slate-600 uppercase">Argument</th>
                    <th className="px-4 py-2 text-xs font-semibold text-slate-600 uppercase">Ask</th>
                    <th className="px-4 py-2 text-xs font-semibold text-slate-600 uppercase">Impact</th>
                  </tr>
                </thead>
                <tbody>
                  <ArgumentGroup title="Profitability" color="red" items={battlecard.key_arguments.profitability} />
                  <ArgumentGroup title="Growth" color="amber" items={battlecard.key_arguments.growth} />
                  <ArgumentGroup title="Others" color="slate" items={battlecard.key_arguments.others} />
                </tbody>
              </table>
            </div>

            <div className="p-5 space-y-6">
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <Target className="w-4 h-4 text-blue-700" />
                  <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide">Negotiation Approach</h3>
                </div>
                <p className="text-xs text-slate-700 leading-relaxed">{battlecard.negotiation_approach}</p>
              </div>

              {battlecard.incentives && (
                <div>
                  <div className="flex items-center gap-2 mb-3">
                    <Gift className="w-4 h-4 text-emerald-600" />
                    <h3 className="text-sm font-bold text-emerald-800 uppercase tracking-wide">Incentives</h3>
                  </div>
                  <ul className="space-y-2">
                    {battlecard.incentives.map((item, i) => (
                      <li key={i} className="flex items-start gap-2 text-xs text-slate-700">
                        <Gift className="w-3.5 h-3.5 text-emerald-500 mt-0.5 shrink-0" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {battlecard.pressures && (
                <div>
                  <div className="flex items-center gap-2 mb-3">
                    <AlertTriangle className="w-4 h-4 text-red-600" />
                    <h3 className="text-sm font-bold text-red-800 uppercase tracking-wide">Pressures</h3>
                  </div>
                  <ul className="space-y-2">
                    {battlecard.pressures.map((item, i) => (
                      <li key={i} className="flex items-start gap-2 text-xs text-slate-700">
                        <AlertTriangle className="w-3.5 h-3.5 text-red-500 mt-0.5 shrink-0" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {battlecard.total_addressable && (
                <div className="border-t border-slate-200 pt-4">
                  <div className="text-xs font-semibold text-slate-500 uppercase mb-1">Total Addressable Value</div>
                  <div className="text-lg font-bold text-blue-800">{battlecard.total_addressable}</div>
                </div>
              )}
            </div>
          </div>
        </div>
      ) : battlecard ? (
        <div className="bg-white border border-t-0 border-slate-200 rounded-b-xl p-6 space-y-6">
          {battlecard.sellthrough && (
            <div>
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wide mb-2">Sell-Through Insights</h3>
              <ul className="space-y-1.5 text-sm text-slate-700">
                {battlecard.sellthrough.split("\n").filter((l) => l.trim()).map((line, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-blue-600 mt-0.5">•</span>
                    <span>{line.replace(/^[•\-*]\s*/, "")}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          {battlecard.switching && (
            <div>
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wide mb-2">Brand Switching</h3>
              <ul className="space-y-1.5 text-sm text-slate-700">
                {battlecard.switching.split("\n").filter((l) => l.trim()).map((line, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-amber-600 mt-0.5">•</span>
                    <span>{line.replace(/^[•\-*]\s*/, "")}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          {battlecard.summary && (
            <div className="border-t border-slate-200 pt-6">
              <h3 className="text-sm font-bold text-blue-800 uppercase tracking-wide mb-2">Executive Summary & Levers</h3>
              <div className="space-y-2">
                {battlecard.summary.split("\n").filter((l) => l.trim()).map((line, i) => (
                  <div key={i} className="p-3 bg-blue-50 border border-blue-200 rounded-lg text-sm text-blue-900">
                    {line.replace(/^[•\-*]\s*/, "")}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      ) : (
        <div className="bg-white border border-t-0 border-slate-200 rounded-b-xl p-8 text-center text-slate-500">
          Failed to generate battlecard. Please try again.
        </div>
      )}
    </div>
  );
}
