import { useState } from "react";
import { Swords, X, Sparkles, Loader2 } from "lucide-react";
import { brandData } from "../data/brandConfig";

const battlecardBrands = [
  "Huggies", "Bugaboo", "Uppababy", "Rascal + Friends", "Maxi-Cosi",
  "Pampers", "Cybex", "Bonds Baby", "Dr Browns", "Infasecure",
];

interface BattlecardData {
  sellthrough: string;
  switching: string;
  summary: string;
}

export default function BattlecardsPage() {
  const [selectedBrand, setSelectedBrand] = useState<string | null>(null);
  const [battlecard, setBattlecard] = useState<BattlecardData | null>(null);
  const [loading, setLoading] = useState(false);
  const [cache, setCache] = useState<Record<string, BattlecardData>>({});

  const generateBattlecard = async (name: string) => {
    setSelectedBrand(name);
    if (cache[name]) {
      setBattlecard(cache[name]);
      return;
    }
    setBattlecard(null);
    setLoading(true);
    try {
      const data = brandData[name];
      const res = await fetch("/api/battlecard/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ brand: name, category: data?.category || "" }),
      });
      const result = await res.json();
      const card = { sellthrough: result.sellthrough, switching: result.switching, summary: result.summary };
      setBattlecard(card);
      setCache((prev) => ({ ...prev, [name]: card }));
    } catch {
      setBattlecard({ sellthrough: "Error loading.", switching: "Error loading.", summary: "Error loading." });
    } finally {
      setLoading(false);
    }
  };

  const closeModal = () => {
    setSelectedBrand(null);
  };

  const selected = selectedBrand ? brandData[selectedBrand] : null;

  return (
    <div className="p-6">
      <div className="flex items-center gap-3 mb-6">
        <Swords className="w-5 h-5 text-blue-700" />
        <h1 className="text-xl font-bold text-slate-900">Negotiation Battlecards</h1>
      </div>

      <p className="text-sm text-slate-500 mb-6">
        AI-generated negotiation briefs powered by Cortex AI. Select a brand to generate a battlecard.
      </p>

      <div className="grid grid-cols-2 gap-3">
        {battlecardBrands.map((name) => {
          const b = brandData[name];
          if (!b) return null;
          return (
            <button
              key={name}
              onClick={() => generateBattlecard(name)}
              className="flex items-center justify-between p-4 bg-white rounded-xl border border-slate-200 shadow-sm hover:border-blue-300 hover:shadow-md transition-all text-left"
            >
              <div>
                <div className="font-medium text-slate-900 text-sm">{b.name}</div>
                <div className="text-xs text-slate-500">{b.category}</div>
              </div>
              <div className="flex items-center gap-1.5 text-xs text-blue-600 font-medium">
                <Sparkles className="w-3.5 h-3.5" />
                Generate
              </div>
            </button>
          );
        })}
      </div>

      {selectedBrand && selected && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-8" onClick={closeModal}>
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[90vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
            <div className="bg-blue-800 text-white p-6 rounded-t-2xl relative">
              <button onClick={closeModal} className="absolute top-4 right-4 text-blue-200 hover:text-white">
                <X className="w-5 h-5" />
              </button>
              <div className="text-xs font-medium text-blue-200 uppercase tracking-wider">AI-Generated Negotiation Battlecard</div>
              <h2 className="mt-1 text-xl font-bold">{selected.name} — {selected.category}</h2>
              <p className="mt-1 text-sm text-blue-200">Generated by Cortex AI | May 2026 | Confidential</p>
            </div>

            <div className="p-6 space-y-6">
              <div>
                <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wide mb-3">Position Metrics</h3>
                <div className="grid grid-cols-5 gap-3">
                  <div className="p-3 bg-slate-50 rounded-lg text-center">
                    <div className="text-[10px] text-slate-500 uppercase">Revenue</div>
                    <div className="font-mono font-bold text-lg">{selected.revenue}</div>
                  </div>
                  <div className="p-3 bg-slate-50 rounded-lg text-center">
                    <div className="text-[10px] text-slate-500 uppercase">Share</div>
                    <div className="font-mono font-bold text-lg">{selected.share}</div>
                  </div>
                  <div className="p-3 bg-slate-50 rounded-lg text-center">
                    <div className="text-[10px] text-slate-500 uppercase">Growth</div>
                    <div className={`font-mono font-bold text-lg ${selected.growth.startsWith("-") ? "text-red-600" : "text-emerald-600"}`}>{selected.growth}</div>
                  </div>
                  <div className="p-3 bg-slate-50 rounded-lg text-center">
                    <div className="text-[10px] text-slate-500 uppercase">RoS</div>
                    <div className="font-mono font-bold text-lg">{selected.ros}</div>
                  </div>
                  <div className="p-3 bg-slate-50 rounded-lg text-center">
                    <div className="text-[10px] text-slate-500 uppercase">Margin</div>
                    <div className="font-mono font-bold text-lg">{selected.margin}</div>
                  </div>
                </div>
              </div>

              {loading ? (
                <div className="flex flex-col items-center justify-center py-8 text-slate-500">
                  <Loader2 className="w-6 h-6 animate-spin text-blue-500 mb-2" />
                  <p className="text-sm">Cortex AI is generating insights...</p>
                </div>
              ) : battlecard ? (
                <>
                  <div>
                    <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wide mb-2">Sell-Through Insights</h3>
                    <ul className="space-y-1.5 text-sm text-slate-700">
                      {battlecard.sellthrough.split("\n").filter(l => l.trim()).map((line, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className="text-blue-600 mt-0.5">•</span>
                          <span>{line.replace(/^[•\-\*]\s*/, "")}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div>
                    <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wide mb-2">Brand Switching</h3>
                    <ul className="space-y-1.5 text-sm text-slate-700">
                      {battlecard.switching.split("\n").filter(l => l.trim()).map((line, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className="text-amber-600 mt-0.5">•</span>
                          <span>{line.replace(/^[•\-\*]\s*/, "")}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="border-t border-slate-200 pt-6">
                    <h3 className="text-sm font-bold text-blue-800 uppercase tracking-wide mb-2">Executive Summary & Levers</h3>
                    <div className="space-y-2">
                      {battlecard.summary.split("\n").filter(l => l.trim()).map((line, i) => (
                        <div key={i} className="p-3 bg-blue-50 border border-blue-200 rounded-lg text-sm text-blue-900">
                          {line.replace(/^[•\-\*]\s*/, "")}
                        </div>
                      ))}
                    </div>
                  </div>
                </>
              ) : null}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
