-- ============================================================
-- Create the Application Package on retailer account
-- ============================================================

USE ROLE ACCOUNTADMIN;

GRANT CREATE APPLICATION PACKAGE ON ACCOUNT TO ROLE ACCOUNTADMIN;

CREATE APPLICATION PACKAGE IF NOT EXISTS SUPPLIER_PORTAL_APP_PACKAGE;

USE APPLICATION PACKAGE SUPPLIER_PORTAL_APP_PACKAGE;

CREATE SCHEMA IF NOT EXISTS APP_ASSETS;
CREATE STAGE IF NOT EXISTS SUPPLIER_PORTAL_APP_PACKAGE.APP_ASSETS.APP_STAGE
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = '|' SKIP_HEADER = 1);

CREATE SCHEMA IF NOT EXISTS SHARED_DATA;
