-- ============================================================
-- Baby Mart Supplier Collaboration Platform
-- 00_setup_infrastructure.sql
-- Run on RETAILER account (Account A)
-- ============================================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS BABY_MART_DEMO;

CREATE SCHEMA IF NOT EXISTS BABY_MART_DEMO.RAW;
CREATE SCHEMA IF NOT EXISTS BABY_MART_DEMO.CURATED;
CREATE SCHEMA IF NOT EXISTS BABY_MART_DEMO.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS BABY_MART_DEMO.AI;
CREATE SCHEMA IF NOT EXISTS BABY_MART_DEMO.APP;

CREATE WAREHOUSE IF NOT EXISTS DEMO_LOAD_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS DEMO_ANALYTICS_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS DEMO_AI_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE;

CREATE STAGE IF NOT EXISTS BABY_MART_DEMO.AI.SEMANTIC_MODEL_STAGE;

CREATE ROLE IF NOT EXISTS BABY_MART_ADMIN;
CREATE ROLE IF NOT EXISTS CATEGORY_MANAGER_ROLE;
CREATE ROLE IF NOT EXISTS DATA_SHARE_ADMIN_ROLE;

GRANT ROLE BABY_MART_ADMIN TO ROLE ACCOUNTADMIN;
GRANT ROLE CATEGORY_MANAGER_ROLE TO ROLE BABY_MART_ADMIN;
GRANT ROLE DATA_SHARE_ADMIN_ROLE TO ROLE BABY_MART_ADMIN;

GRANT USAGE ON DATABASE BABY_MART_DEMO TO ROLE BABY_MART_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BABY_MART_DEMO TO ROLE BABY_MART_ADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE BABY_MART_DEMO TO ROLE BABY_MART_ADMIN;

GRANT USAGE ON WAREHOUSE DEMO_ANALYTICS_WH TO ROLE CATEGORY_MANAGER_ROLE;
GRANT USAGE ON WAREHOUSE DEMO_AI_WH TO ROLE CATEGORY_MANAGER_ROLE;
GRANT USAGE ON DATABASE BABY_MART_DEMO TO ROLE CATEGORY_MANAGER_ROLE;
GRANT USAGE ON SCHEMA BABY_MART_DEMO.ANALYTICS TO ROLE CATEGORY_MANAGER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA BABY_MART_DEMO.ANALYTICS TO ROLE CATEGORY_MANAGER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA BABY_MART_DEMO.ANALYTICS TO ROLE CATEGORY_MANAGER_ROLE;
