CREATE APPLICATION ROLE IF NOT EXISTS app_user;
CREATE SCHEMA IF NOT EXISTS APP_CODE;

CREATE OR REPLACE VIEW APP_CODE.SELLTHROUGH AS
  SELECT * FROM SHARED_DATA.VW_SUPPLIER_SELLTHROUGH;

CREATE OR REPLACE VIEW APP_CODE.SEGMENTS AS
  SELECT * FROM SHARED_DATA.VW_SUPPLIER_SEGMENTS;

CREATE OR REPLACE VIEW APP_CODE.SWITCHING AS
  SELECT * FROM SHARED_DATA.VW_SUPPLIER_SWITCHING;

CREATE OR REPLACE VIEW APP_CODE.INVENTORY AS
  SELECT * FROM SHARED_DATA.VW_SUPPLIER_INVENTORY;

CREATE STREAMLIT IF NOT EXISTS APP_CODE.SUPPLIER_PORTAL
  FROM '/streamlit'
  MAIN_FILE = 'supplier_portal.py';

GRANT USAGE ON SCHEMA APP_CODE TO APPLICATION ROLE app_user;
GRANT SELECT ON ALL VIEWS IN SCHEMA APP_CODE TO APPLICATION ROLE app_user;
GRANT USAGE ON STREAMLIT APP_CODE.SUPPLIER_PORTAL TO APPLICATION ROLE app_user;
