-- ============================================================
-- Step 1: Create Application Package
-- One package per supplier. Change the name for each supplier.
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- For Bugaboo:
CREATE APPLICATION PACKAGE IF NOT EXISTS SUPPLIER_PORTAL_BUGABOO_PACKAGE
  ENABLE_RELEASE_CHANNELS = FALSE;

-- For Huggies:
-- CREATE APPLICATION PACKAGE IF NOT EXISTS SUPPLIER_PORTAL_HUGGIES_PACKAGE
--   ENABLE_RELEASE_CHANNELS = FALSE;

-- Set up internal schemas
USE APPLICATION PACKAGE SUPPLIER_PORTAL_BUGABOO_PACKAGE;
CREATE SCHEMA IF NOT EXISTS APP_ASSETS;
CREATE STAGE IF NOT EXISTS SUPPLIER_PORTAL_BUGABOO_PACKAGE.APP_ASSETS.APP_STAGE;
CREATE SCHEMA IF NOT EXISTS SHARED_DATA;

-- Grant reference to the retailer database
GRANT REFERENCE_USAGE ON DATABASE BABY_MART_DEMO
  TO SHARE IN APPLICATION PACKAGE SUPPLIER_PORTAL_BUGABOO_PACKAGE;
