-- ============================================================
-- Step 2: Create supplier-filtered shared data views
-- Change the WHERE clause for each supplier.
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ===== BUGABOO =====
CREATE OR REPLACE VIEW SUPPLIER_PORTAL_BUGABOO_PACKAGE.SHARED_DATA.VW_SUPPLIER_SELLTHROUGH AS
  SELECT * FROM BABY_MART_DEMO.ANALYTICS.VW_SUPPLIER_SELLTHROUGH
  WHERE supplier_name = 'Bugaboo Australia';

CREATE OR REPLACE VIEW SUPPLIER_PORTAL_BUGABOO_PACKAGE.SHARED_DATA.VW_SUPPLIER_SEGMENTS AS
  SELECT * FROM BABY_MART_DEMO.ANALYTICS.VW_SUPPLIER_SEGMENTS
  WHERE supplier_name = 'Bugaboo Australia';

CREATE OR REPLACE VIEW SUPPLIER_PORTAL_BUGABOO_PACKAGE.SHARED_DATA.VW_SUPPLIER_SWITCHING AS
  SELECT * FROM BABY_MART_DEMO.ANALYTICS.VW_SUPPLIER_SWITCHING
  WHERE from_brand = 'Bugaboo' OR to_brand = 'Bugaboo';

CREATE OR REPLACE VIEW SUPPLIER_PORTAL_BUGABOO_PACKAGE.SHARED_DATA.VW_SUPPLIER_INVENTORY AS
  SELECT * FROM BABY_MART_DEMO.ANALYTICS.VW_SUPPLIER_INVENTORY
  WHERE supplier_name = 'Bugaboo Australia';

-- Grant to the share
GRANT USAGE ON SCHEMA SUPPLIER_PORTAL_BUGABOO_PACKAGE.SHARED_DATA
  TO SHARE IN APPLICATION PACKAGE SUPPLIER_PORTAL_BUGABOO_PACKAGE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPPLIER_PORTAL_BUGABOO_PACKAGE.SHARED_DATA
  TO SHARE IN APPLICATION PACKAGE SUPPLIER_PORTAL_BUGABOO_PACKAGE;
