CREATE APPLICATION ROLE IF NOT EXISTS app_user;
CREATE SCHEMA IF NOT EXISTS APP_CODE;

CREATE OR REPLACE VIEW APP_CODE.SELLTHROUGH AS
  SELECT * FROM SHARED_DATA.VW_SUPPLIER_SELLTHROUGH;

CREATE OR REPLACE VIEW APP_CODE.SEGMENTS AS
  SELECT * FROM SHARED_DATA.VW_SUPPLIER_SEGMENTS;

CREATE OR REPLACE VIEW APP_CODE.SWITCHING AS
  SELECT * FROM SHARED_DATA.VW_SUPPLIER_SWITCHING;

CREATE OR REPLACE VIEW APP_CODE.INVENTORY AS
  SELECT * FROM SHARED_DATA.VW_SUPPLIER_INVENTORY;

CREATE OR REPLACE SEMANTIC VIEW APP_CODE.SUPPLIER_SEMANTIC_VIEW
  TABLES (
    SELLTHROUGH AS APP_CODE.SELLTHROUGH,
    SEGMENTS AS APP_CODE.SEGMENTS,
    SWITCHING AS APP_CODE.SWITCHING
  )
  DIMENSIONS (
    SELLTHROUGH.SUPPLIER_NAME AS SUPPLIER_NAME COMMENT='Supplier company name',
    SELLTHROUGH.BRAND_NAME AS BRAND_NAME COMMENT='Product brand name',
    SELLTHROUGH.CATEGORY AS CATEGORY COMMENT='Product category',
    SELLTHROUGH.CLASS AS CLASS COMMENT='Product class within category',
    SELLTHROUGH.STORE_NAME AS STORE_NAME COMMENT='Store name',
    SELLTHROUGH.STATE AS STATE COMMENT='Australian state (VIC, NSW, QLD, SA, WA, TAS, ACT, NT)',
    SELLTHROUGH.REGION AS REGION COMMENT='Region type (Metro, Regional)',
    SELLTHROUGH.FISCAL_WEEK AS FISCAL_WEEK COMMENT='Fiscal week number',
    SELLTHROUGH.FISCAL_MONTH AS FISCAL_MONTH COMMENT='Fiscal month',
    SELLTHROUGH.FISCAL_QUARTER AS FISCAL_QUARTER COMMENT='Fiscal quarter',
    SELLTHROUGH.FISCAL_YEAR AS FISCAL_YEAR COMMENT='Fiscal year',
    SEGMENTS.SUPPLIER_NAME AS SUPPLIER_NAME COMMENT='Supplier name',
    SEGMENTS.BRAND_NAME AS BRAND_NAME COMMENT='Brand name',
    SEGMENTS.SEGMENT_NAME AS SEGMENT_NAME COMMENT='Customer segment',
    SEGMENTS.FISCAL_YEAR AS FISCAL_YEAR COMMENT='Fiscal year',
    SEGMENTS.FISCAL_QUARTER AS FISCAL_QUARTER COMMENT='Fiscal quarter',
    SWITCHING.CATEGORY AS CATEGORY COMMENT='Product category',
    SWITCHING.CLASS AS CLASS COMMENT='Product class',
    SWITCHING.FROM_BRAND AS FROM_BRAND COMMENT='Brand customers switched from',
    SWITCHING.TO_BRAND AS TO_BRAND COMMENT='Brand customers switched to'
  );

CREATE OR REPLACE AGENT APP_CODE.SUPPLIER_AGENT
  FROM SPECIFICATION $$
  models:
    orchestration: auto

  instructions:
    system: "You are a retail performance analyst for Baby Mart helping a supplier understand their product performance. Be concise, data-driven, and actionable. Always include specific numbers, percentages, and dollar amounts. Suggest actions when issues are found. The SELLTHROUGH table has columns UNITS_SOLD, REVENUE, AVG_PRICE, MARGIN, RATE_OF_SALE. The SEGMENTS table has CUSTOMER_COUNT, REVENUE, UNITS, TRANSACTION_COUNT. The SWITCHING table has SWITCH_COUNT, CUSTOMER_COUNT."

  tools:
    - tool_spec:
        type: "cortex_analyst_text_to_sql"
        name: "supplier_analytics"
        description: "Query supplier performance data including weekly sell-through by state and store, customer segment breakdown, and brand switching dynamics."

  tool_resources:
    supplier_analytics:
      semantic_view: "APP_CODE.SUPPLIER_SEMANTIC_VIEW"
      execution_environment:
        type: warehouse
        warehouse: "COMPUTE_WH"
  $$;

CREATE STREAMLIT IF NOT EXISTS APP_CODE.SUPPLIER_PORTAL
  FROM '/streamlit'
  MAIN_FILE = 'supplier_portal.py';

GRANT USAGE ON SCHEMA APP_CODE TO APPLICATION ROLE app_user;
GRANT SELECT ON ALL VIEWS IN SCHEMA APP_CODE TO APPLICATION ROLE app_user;
GRANT SELECT ON SEMANTIC VIEW APP_CODE.SUPPLIER_SEMANTIC_VIEW TO APPLICATION ROLE app_user;
GRANT USAGE ON AGENT APP_CODE.SUPPLIER_AGENT TO APPLICATION ROLE app_user;
GRANT USAGE ON STREAMLIT APP_CODE.SUPPLIER_PORTAL TO APPLICATION ROLE app_user;
